import 'antd/dist/antd.css'; // or 'antd/dist/antd.less'
import Head from 'next/head';
import { Footer, Header, Main } from '../components';
import Styles from '../styles/Index.module.scss';
export default function Home() {
  return (
    <div className={Styles.container}>
      <Head>
        <title>Ellen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Footer />
    </div>
  )
}
